services:
  db:
    build: ./db
    image: postgres:17
    environment:
      POSTGRES_USER: normativas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: normativas
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data